.PHONY: all clean

all: 
	pdflatex projektmanagement.tex
	pdflatex projektmanagement.tex
	pdflatex projektmanagement.tex

clean:
	rm -f *.aux
	rm -f *.bbl
	rm -f *.blg
	rm -f *.log
	rm -f *.out
	rm -f *.toc
	rm -f *.lot
	rm -f *.lof

