.PHONY: all clean

all: 
	pdflatex pres.tex
	#bibtex   pres.aux
	pdflatex pres.tex
	pdflatex pres.tex
	pdflatex pres.tex

clean:
	rm -f *.aux
	rm -f *.bbl
	rm -f *.blg
	rm -f *.log
	rm -f *.nav
	rm -f *.out
	rm -f *.snm
	rm -f *.toc
	rm -f *.lot
	rm -f *.lof

